#!/bin/sh
set -e

for x in emcc em++ emconfigure emmake wasm2wast wast2wasm wasmdump wasm-interp \
         s2wasm wasm-opt wasm-as wasm-dis wasm-shell wasm d8; do
  update-alternatives --remove $x /opt/wasm/bin/$x
done
